// Code generated by protoc-gen-go.
// source: nfs.proto
// DO NOT EDIT!

/*
Package nfs is a generated protocol buffer package.

It is generated from these files:
	nfs.proto

It has these top-level messages:
	FileHandle
	Attribute
	Dirent
	LookupArgs
	LookupReturn
	RootArgs
	RootReturn
	CreateArgs
	CreateReturn
	RemoveArgs
	RemoveReturn
	ReadArgs
	ReadReturn
	WriteArgs
	WriteReturn
	ReaddirArgs
	ReaddirReturn
	GetAttrArgs
	GetAttrReturn
	MkdirArgs
	MkdirReturn
	RenameArgs
	RenameReturn
*/
package nfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// File handle type, need inode #, filesystem & generation #.
type FileHandle struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Genum uint64 `protobuf:"varint,2,opt,name=genum" json:"genum,omitempty"`
}

func (m *FileHandle) Reset()                    { *m = FileHandle{} }
func (m *FileHandle) String() string            { return proto.CompactTextString(m) }
func (*FileHandle) ProtoMessage()               {}
func (*FileHandle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Attribute struct {
	Mode      uint32 `protobuf:"varint,1,opt,name=mode" json:"mode,omitempty"`
	Uid       uint32 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Gid       uint32 `protobuf:"varint,3,opt,name=gid" json:"gid,omitempty"`
	Size      uint64 `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Atime     uint64 `protobuf:"varint,5,opt,name=atime" json:"atime,omitempty"`
	Mtime     uint64 `protobuf:"varint,6,opt,name=mtime" json:"mtime,omitempty"`
	AtimeNsec uint32 `protobuf:"varint,7,opt,name=atime_nsec,json=atimeNsec" json:"atime_nsec,omitempty"`
	MtimeNsec uint32 `protobuf:"varint,8,opt,name=mtime_nsec,json=mtimeNsec" json:"mtime_nsec,omitempty"`
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// nfs protocol describes using cookies (each entry links to the next),
// but we can assume for now that it's unnecessary with gorpc
// model this after fuse.Dirent
type Dirent struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Mode  uint32 `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
}

func (m *Dirent) Reset()                    { *m = Dirent{} }
func (m *Dirent) String() string            { return proto.CompactTextString(m) }
func (*Dirent) ProtoMessage()               {}
func (*Dirent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Hacky solution to multiple parameter, just follow convention: MethodNameArgs
type LookupArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *LookupArgs) Reset()                    { *m = LookupArgs{} }
func (m *LookupArgs) String() string            { return proto.CompactTextString(m) }
func (*LookupArgs) ProtoMessage()               {}
func (*LookupArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LookupArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

// Hacky solution to multiple retval, just follow convention: MethodNameReturn
type LookupReturn struct {
	Fh   *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Attr *Attribute  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *LookupReturn) Reset()                    { *m = LookupReturn{} }
func (m *LookupReturn) String() string            { return proto.CompactTextString(m) }
func (*LookupReturn) ProtoMessage()               {}
func (*LookupReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LookupReturn) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

func (m *LookupReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type RootArgs struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *RootArgs) Reset()                    { *m = RootArgs{} }
func (m *RootArgs) String() string            { return proto.CompactTextString(m) }
func (*RootArgs) ProtoMessage()               {}
func (*RootArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type RootReturn struct {
	Fh   *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Attr *Attribute  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *RootReturn) Reset()                    { *m = RootReturn{} }
func (m *RootReturn) String() string            { return proto.CompactTextString(m) }
func (*RootReturn) ProtoMessage()               {}
func (*RootReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RootReturn) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

func (m *RootReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type CreateArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attr  *Attribute  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *CreateArgs) Reset()                    { *m = CreateArgs{} }
func (m *CreateArgs) String() string            { return proto.CompactTextString(m) }
func (*CreateArgs) ProtoMessage()               {}
func (*CreateArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

func (m *CreateArgs) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type CreateReturn struct {
	Newfh *FileHandle `protobuf:"bytes,1,opt,name=newfh" json:"newfh,omitempty"`
	Attr  *Attribute  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *CreateReturn) Reset()                    { *m = CreateReturn{} }
func (m *CreateReturn) String() string            { return proto.CompactTextString(m) }
func (*CreateReturn) ProtoMessage()               {}
func (*CreateReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateReturn) GetNewfh() *FileHandle {
	if m != nil {
		return m.Newfh
	}
	return nil
}

func (m *CreateReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type RemoveArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IsDir bool        `protobuf:"varint,3,opt,name=isDir" json:"isDir,omitempty"`
}

func (m *RemoveArgs) Reset()                    { *m = RemoveArgs{} }
func (m *RemoveArgs) String() string            { return proto.CompactTextString(m) }
func (*RemoveArgs) ProtoMessage()               {}
func (*RemoveArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RemoveArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

type RemoveReturn struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *RemoveReturn) Reset()                    { *m = RemoveReturn{} }
func (m *RemoveReturn) String() string            { return proto.CompactTextString(m) }
func (*RemoveReturn) ProtoMessage()               {}
func (*RemoveReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type ReadArgs struct {
	Fh     *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Offset int64       `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count  int64       `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *ReadArgs) Reset()                    { *m = ReadArgs{} }
func (m *ReadArgs) String() string            { return proto.CompactTextString(m) }
func (*ReadArgs) ProtoMessage()               {}
func (*ReadArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ReadArgs) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

type ReadReturn struct {
	Attr *Attribute `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
	Data []byte     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ReadReturn) Reset()                    { *m = ReadReturn{} }
func (m *ReadReturn) String() string            { return proto.CompactTextString(m) }
func (*ReadReturn) ProtoMessage()               {}
func (*ReadReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ReadReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type WriteArgs struct {
	Fh     *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Offset int64       `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count  int64       `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Data   []byte      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *WriteArgs) Reset()                    { *m = WriteArgs{} }
func (m *WriteArgs) String() string            { return proto.CompactTextString(m) }
func (*WriteArgs) ProtoMessage()               {}
func (*WriteArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *WriteArgs) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

// Yes, even for single retval's, follow convention for consistency
type WriteReturn struct {
	Attr *Attribute `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
}

func (m *WriteReturn) Reset()                    { *m = WriteReturn{} }
func (m *WriteReturn) String() string            { return proto.CompactTextString(m) }
func (*WriteReturn) ProtoMessage()               {}
func (*WriteReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *WriteReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type ReaddirArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Count uint64      `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *ReaddirArgs) Reset()                    { *m = ReaddirArgs{} }
func (m *ReaddirArgs) String() string            { return proto.CompactTextString(m) }
func (*ReaddirArgs) ProtoMessage()               {}
func (*ReaddirArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ReaddirArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

type ReaddirReturn struct {
	// directory entries
	Entries []*Dirent `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *ReaddirReturn) Reset()                    { *m = ReaddirReturn{} }
func (m *ReaddirReturn) String() string            { return proto.CompactTextString(m) }
func (*ReaddirReturn) ProtoMessage()               {}
func (*ReaddirReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ReaddirReturn) GetEntries() []*Dirent {
	if m != nil {
		return m.Entries
	}
	return nil
}

type GetAttrArgs struct {
	Fh *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
}

func (m *GetAttrArgs) Reset()                    { *m = GetAttrArgs{} }
func (m *GetAttrArgs) String() string            { return proto.CompactTextString(m) }
func (*GetAttrArgs) ProtoMessage()               {}
func (*GetAttrArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetAttrArgs) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

type GetAttrReturn struct {
	Attr *Attribute `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
}

func (m *GetAttrReturn) Reset()                    { *m = GetAttrReturn{} }
func (m *GetAttrReturn) String() string            { return proto.CompactTextString(m) }
func (*GetAttrReturn) ProtoMessage()               {}
func (*GetAttrReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetAttrReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type MkdirArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attr  *Attribute  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *MkdirArgs) Reset()                    { *m = MkdirArgs{} }
func (m *MkdirArgs) String() string            { return proto.CompactTextString(m) }
func (*MkdirArgs) ProtoMessage()               {}
func (*MkdirArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *MkdirArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

func (m *MkdirArgs) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type MkdirReturn struct {
	Fh   *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Attr *Attribute  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *MkdirReturn) Reset()                    { *m = MkdirReturn{} }
func (m *MkdirReturn) String() string            { return proto.CompactTextString(m) }
func (*MkdirReturn) ProtoMessage()               {}
func (*MkdirReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MkdirReturn) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

func (m *MkdirReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type RenameArgs struct {
	Dirfh  *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name   string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tofh   *FileHandle `protobuf:"bytes,3,opt,name=tofh" json:"tofh,omitempty"`
	Toname string      `protobuf:"bytes,4,opt,name=toname" json:"toname,omitempty"`
}

func (m *RenameArgs) Reset()                    { *m = RenameArgs{} }
func (m *RenameArgs) String() string            { return proto.CompactTextString(m) }
func (*RenameArgs) ProtoMessage()               {}
func (*RenameArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RenameArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

func (m *RenameArgs) GetTofh() *FileHandle {
	if m != nil {
		return m.Tofh
	}
	return nil
}

type RenameReturn struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *RenameReturn) Reset()                    { *m = RenameReturn{} }
func (m *RenameReturn) String() string            { return proto.CompactTextString(m) }
func (*RenameReturn) ProtoMessage()               {}
func (*RenameReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func init() {
	proto.RegisterType((*FileHandle)(nil), "nfs.FileHandle")
	proto.RegisterType((*Attribute)(nil), "nfs.Attribute")
	proto.RegisterType((*Dirent)(nil), "nfs.Dirent")
	proto.RegisterType((*LookupArgs)(nil), "nfs.LookupArgs")
	proto.RegisterType((*LookupReturn)(nil), "nfs.LookupReturn")
	proto.RegisterType((*RootArgs)(nil), "nfs.RootArgs")
	proto.RegisterType((*RootReturn)(nil), "nfs.RootReturn")
	proto.RegisterType((*CreateArgs)(nil), "nfs.CreateArgs")
	proto.RegisterType((*CreateReturn)(nil), "nfs.CreateReturn")
	proto.RegisterType((*RemoveArgs)(nil), "nfs.RemoveArgs")
	proto.RegisterType((*RemoveReturn)(nil), "nfs.RemoveReturn")
	proto.RegisterType((*ReadArgs)(nil), "nfs.ReadArgs")
	proto.RegisterType((*ReadReturn)(nil), "nfs.ReadReturn")
	proto.RegisterType((*WriteArgs)(nil), "nfs.WriteArgs")
	proto.RegisterType((*WriteReturn)(nil), "nfs.WriteReturn")
	proto.RegisterType((*ReaddirArgs)(nil), "nfs.ReaddirArgs")
	proto.RegisterType((*ReaddirReturn)(nil), "nfs.ReaddirReturn")
	proto.RegisterType((*GetAttrArgs)(nil), "nfs.GetAttrArgs")
	proto.RegisterType((*GetAttrReturn)(nil), "nfs.GetAttrReturn")
	proto.RegisterType((*MkdirArgs)(nil), "nfs.MkdirArgs")
	proto.RegisterType((*MkdirReturn)(nil), "nfs.MkdirReturn")
	proto.RegisterType((*RenameArgs)(nil), "nfs.RenameArgs")
	proto.RegisterType((*RenameReturn)(nil), "nfs.RenameReturn")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for NFS service

type NFSClient interface {
	// No null call for now (not sure if needed since grpc is smart itself!)
	Root(ctx context.Context, in *RootArgs, opts ...grpc.CallOption) (*RootReturn, error)
	Lookup(ctx context.Context, in *LookupArgs, opts ...grpc.CallOption) (*LookupReturn, error)
	Create(ctx context.Context, in *CreateArgs, opts ...grpc.CallOption) (*CreateReturn, error)
	Remove(ctx context.Context, in *RemoveArgs, opts ...grpc.CallOption) (*RemoveReturn, error)
	Read(ctx context.Context, in *ReadArgs, opts ...grpc.CallOption) (*ReadReturn, error)
	Write(ctx context.Context, in *WriteArgs, opts ...grpc.CallOption) (*WriteReturn, error)
	Readdir(ctx context.Context, in *ReaddirArgs, opts ...grpc.CallOption) (*ReaddirReturn, error)
	Getattr(ctx context.Context, in *GetAttrArgs, opts ...grpc.CallOption) (*GetAttrReturn, error)
	Mkdir(ctx context.Context, in *MkdirArgs, opts ...grpc.CallOption) (*MkdirReturn, error)
	Rename(ctx context.Context, in *RenameArgs, opts ...grpc.CallOption) (*RenameReturn, error)
}

type nFSClient struct {
	cc *grpc.ClientConn
}

func NewNFSClient(cc *grpc.ClientConn) NFSClient {
	return &nFSClient{cc}
}

func (c *nFSClient) Root(ctx context.Context, in *RootArgs, opts ...grpc.CallOption) (*RootReturn, error) {
	out := new(RootReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/root", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Lookup(ctx context.Context, in *LookupArgs, opts ...grpc.CallOption) (*LookupReturn, error) {
	out := new(LookupReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Create(ctx context.Context, in *CreateArgs, opts ...grpc.CallOption) (*CreateReturn, error) {
	out := new(CreateReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Remove(ctx context.Context, in *RemoveArgs, opts ...grpc.CallOption) (*RemoveReturn, error) {
	out := new(RemoveReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Read(ctx context.Context, in *ReadArgs, opts ...grpc.CallOption) (*ReadReturn, error) {
	out := new(ReadReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Write(ctx context.Context, in *WriteArgs, opts ...grpc.CallOption) (*WriteReturn, error) {
	out := new(WriteReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Readdir(ctx context.Context, in *ReaddirArgs, opts ...grpc.CallOption) (*ReaddirReturn, error) {
	out := new(ReaddirReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/readdir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Getattr(ctx context.Context, in *GetAttrArgs, opts ...grpc.CallOption) (*GetAttrReturn, error) {
	out := new(GetAttrReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/getattr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Mkdir(ctx context.Context, in *MkdirArgs, opts ...grpc.CallOption) (*MkdirReturn, error) {
	out := new(MkdirReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/mkdir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Rename(ctx context.Context, in *RenameArgs, opts ...grpc.CallOption) (*RenameReturn, error) {
	out := new(RenameReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/rename", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NFS service

type NFSServer interface {
	// No null call for now (not sure if needed since grpc is smart itself!)
	Root(context.Context, *RootArgs) (*RootReturn, error)
	Lookup(context.Context, *LookupArgs) (*LookupReturn, error)
	Create(context.Context, *CreateArgs) (*CreateReturn, error)
	Remove(context.Context, *RemoveArgs) (*RemoveReturn, error)
	Read(context.Context, *ReadArgs) (*ReadReturn, error)
	Write(context.Context, *WriteArgs) (*WriteReturn, error)
	Readdir(context.Context, *ReaddirArgs) (*ReaddirReturn, error)
	Getattr(context.Context, *GetAttrArgs) (*GetAttrReturn, error)
	Mkdir(context.Context, *MkdirArgs) (*MkdirReturn, error)
	Rename(context.Context, *RenameArgs) (*RenameReturn, error)
}

func RegisterNFSServer(s *grpc.Server, srv NFSServer) {
	s.RegisterService(&_NFS_serviceDesc, srv)
}

func _NFS_Root_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RootArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Root(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Root",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Root(ctx, req.(*RootArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Lookup(ctx, req.(*LookupArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Create(ctx, req.(*CreateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Remove(ctx, req.(*RemoveArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Read(ctx, req.(*ReadArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Write(ctx, req.(*WriteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Readdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReaddirArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Readdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Readdir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Readdir(ctx, req.(*ReaddirArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Getattr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttrArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Getattr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Getattr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Getattr(ctx, req.(*GetAttrArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Mkdir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Mkdir(ctx, req.(*MkdirArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Rename(ctx, req.(*RenameArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _NFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nfs.NFS",
	HandlerType: (*NFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "root",
			Handler:    _NFS_Root_Handler,
		},
		{
			MethodName: "lookup",
			Handler:    _NFS_Lookup_Handler,
		},
		{
			MethodName: "create",
			Handler:    _NFS_Create_Handler,
		},
		{
			MethodName: "remove",
			Handler:    _NFS_Remove_Handler,
		},
		{
			MethodName: "read",
			Handler:    _NFS_Read_Handler,
		},
		{
			MethodName: "write",
			Handler:    _NFS_Write_Handler,
		},
		{
			MethodName: "readdir",
			Handler:    _NFS_Readdir_Handler,
		},
		{
			MethodName: "getattr",
			Handler:    _NFS_Getattr_Handler,
		},
		{
			MethodName: "mkdir",
			Handler:    _NFS_Mkdir_Handler,
		},
		{
			MethodName: "rename",
			Handler:    _NFS_Rename_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("nfs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 743 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6b, 0x14, 0x3d,
	0x14, 0xde, 0xed, 0xcc, 0x6e, 0x77, 0xcf, 0xec, 0xbe, 0xed, 0x1b, 0xa4, 0x2c, 0x0b, 0x7e, 0x10,
	0xa9, 0x14, 0x84, 0x85, 0x6e, 0x41, 0xbc, 0x2d, 0x96, 0x56, 0x44, 0x0b, 0xa6, 0x17, 0xd2, 0x0b,
	0x91, 0xe9, 0x4e, 0x66, 0x1b, 0xdb, 0x49, 0x4a, 0x26, 0x63, 0xc1, 0x6b, 0xff, 0x98, 0x3f, 0xc3,
	0x7f, 0x23, 0x39, 0xc9, 0x64, 0x46, 0xb4, 0xb5, 0xb5, 0xbd, 0xcb, 0xf9, 0x7e, 0x9e, 0x93, 0x93,
	0x33, 0x03, 0x43, 0x99, 0x97, 0xb3, 0x0b, 0xad, 0x8c, 0x22, 0x91, 0xcc, 0x4b, 0xfa, 0x12, 0x60,
	0x5f, 0x9c, 0xf3, 0xd7, 0xa9, 0xcc, 0xce, 0x39, 0x79, 0x00, 0x3d, 0x21, 0x55, 0xc6, 0x27, 0xdd,
	0x27, 0xdd, 0xad, 0x98, 0x39, 0xc1, 0x6a, 0x97, 0x5c, 0x56, 0xc5, 0x64, 0xc5, 0x69, 0x51, 0xa0,
	0xdf, 0xbb, 0x30, 0xdc, 0x35, 0x46, 0x8b, 0x93, 0xca, 0x70, 0x42, 0x20, 0x2e, 0xea, 0xc0, 0x31,
	0xc3, 0x33, 0x59, 0x87, 0xa8, 0x12, 0x19, 0x46, 0x8d, 0x99, 0x3d, 0x5a, 0xcd, 0x52, 0x64, 0x93,
	0xc8, 0x69, 0x96, 0x22, 0xb3, 0x71, 0xa5, 0xf8, 0xca, 0x27, 0x31, 0xa6, 0xc6, 0xb3, 0xad, 0x97,
	0x1a, 0x51, 0xf0, 0x49, 0xcf, 0xd5, 0x43, 0xc1, 0x6a, 0x0b, 0xd4, 0xf6, 0x9d, 0x16, 0x05, 0xf2,
	0x10, 0x00, 0xcd, 0x9f, 0x64, 0xc9, 0x17, 0x93, 0x55, 0x4c, 0x3c, 0x44, 0xcd, 0x61, 0xc9, 0x17,
	0xd6, 0x5c, 0x34, 0xe6, 0x81, 0x33, 0x17, 0xb5, 0x99, 0xee, 0x43, 0x7f, 0x4f, 0x68, 0x2e, 0xcd,
	0x15, 0xcc, 0x09, 0xc4, 0x32, 0x2d, 0x38, 0x52, 0x18, 0x32, 0x3c, 0x07, 0xa6, 0x51, 0xc3, 0x94,
	0x1e, 0x00, 0xbc, 0x55, 0xea, 0xac, 0xba, 0xd8, 0xd5, 0xcb, 0x92, 0x6c, 0x42, 0x2f, 0x13, 0x3a,
	0x3f, 0xc5, 0x5c, 0xc9, 0x7c, 0x6d, 0x66, 0x7b, 0xde, 0x74, 0x99, 0x39, 0xeb, 0x9f, 0x92, 0xd3,
	0x23, 0x18, 0xb9, 0x44, 0x8c, 0x9b, 0x4a, 0x4b, 0xf2, 0x18, 0x56, 0xae, 0xce, 0xb3, 0x92, 0x9f,
	0x12, 0x0a, 0x71, 0x6a, 0x8c, 0xc6, 0x24, 0xc9, 0xfc, 0x3f, 0x74, 0x09, 0xb7, 0xc2, 0xd0, 0x46,
	0x1f, 0xc1, 0x80, 0x29, 0x65, 0x10, 0x1b, 0x81, 0xf8, 0x22, 0x35, 0x2e, 0xe5, 0x90, 0xe1, 0x99,
	0xbe, 0x07, 0xb0, 0xf6, 0xfb, 0x2c, 0x79, 0x06, 0xf0, 0x4a, 0xf3, 0xd4, 0xf0, 0x3b, 0x36, 0x24,
	0x14, 0x8b, 0xae, 0x29, 0x76, 0x0c, 0x23, 0x57, 0xcc, 0x33, 0xd8, 0x84, 0x9e, 0xe4, 0x97, 0xd7,
	0x94, 0x43, 0xeb, 0x8d, 0x78, 0x7c, 0x04, 0x60, 0xbc, 0x50, 0x5f, 0xee, 0xcc, 0xc3, 0xce, 0x57,
	0xb9, 0x27, 0x1c, 0x91, 0x01, 0x73, 0x02, 0x7d, 0x06, 0x23, 0x97, 0xde, 0x23, 0xdf, 0x80, 0x7e,
	0x69, 0x52, 0x53, 0x95, 0x58, 0xa1, 0xc7, 0xbc, 0x44, 0x8f, 0x61, 0xc0, 0x78, 0x9a, 0x21, 0x88,
	0xbf, 0xde, 0xcf, 0x06, 0xf4, 0x55, 0x9e, 0x97, 0xdc, 0x20, 0x80, 0x88, 0x79, 0xc9, 0x42, 0x58,
	0xa8, 0x4a, 0x1a, 0x84, 0x10, 0x31, 0x27, 0xd0, 0x3d, 0xcb, 0x30, 0xcd, 0x3c, 0x80, 0xba, 0x27,
	0xdd, 0xab, 0x7b, 0x62, 0xe9, 0x65, 0xa9, 0x49, 0x31, 0xfb, 0x88, 0xe1, 0x99, 0x4a, 0x18, 0x7e,
	0xd0, 0xc2, 0x5f, 0xf7, 0xfd, 0x22, 0x0c, 0xf5, 0xe2, 0x56, 0xbd, 0x6d, 0x48, 0xb0, 0xde, 0xcd,
	0x61, 0xd3, 0x37, 0x90, 0x58, 0xa2, 0x99, 0xd0, 0xb7, 0xb9, 0xcb, 0x00, 0xc9, 0xef, 0x3e, 0xd7,
	0xb4, 0x17, 0x30, 0xf6, 0xb9, 0xc2, 0xc8, 0xad, 0x72, 0x69, 0xb4, 0xe0, 0xf6, 0xe6, 0xa2, 0xad,
	0x64, 0x9e, 0x60, 0x3e, 0xb7, 0x5c, 0x58, 0x6d, 0xa3, 0x33, 0x48, 0x0e, 0xb8, 0xb1, 0xc8, 0x6e,
	0xd4, 0x28, 0xba, 0x03, 0x63, 0xef, 0x7f, 0x0b, 0xa2, 0x9f, 0x61, 0xf8, 0xee, 0xec, 0x96, 0x34,
	0xff, 0xf5, 0xe9, 0x31, 0x48, 0xb0, 0xd6, 0x7d, 0xee, 0x8e, 0x6f, 0x5d, 0x3b, 0x92, 0x16, 0xc2,
	0x5d, 0x19, 0x3c, 0x85, 0xd8, 0xa8, 0xfc, 0xd4, 0x33, 0xf8, 0x2d, 0x12, 0x8d, 0x76, 0x18, 0x8d,
	0xc2, 0xd0, 0x18, 0x43, 0xbd, 0xe4, 0xde, 0xa6, 0x3d, 0x5d, 0xff, 0x36, 0xe7, 0x3f, 0x22, 0x88,
	0x0e, 0xf7, 0x8f, 0xc8, 0x16, 0xc4, 0x5a, 0x29, 0x43, 0xc6, 0x58, 0xa6, 0x5e, 0xb8, 0xd3, 0xb5,
	0x20, 0xba, 0x3c, 0xb4, 0x43, 0x66, 0xd0, 0x3f, 0xc7, 0x25, 0x4f, 0x9c, 0xb1, 0xf9, 0x74, 0x4c,
	0xff, 0x6f, 0x29, 0xda, 0xfe, 0x0b, 0xdc, 0x6f, 0xde, 0xbf, 0xd9, 0xac, 0xde, 0xbf, 0xbd, 0xfd,
	0x9c, 0xbf, 0xc6, 0xad, 0xe2, 0xfd, 0x9b, 0x0d, 0xe6, 0xfd, 0xdb, 0x3b, 0x87, 0x76, 0x10, 0x39,
	0x4f, 0xb3, 0x1a, 0xb9, 0x5f, 0x34, 0x35, 0xf2, 0xb0, 0x1c, 0x68, 0x87, 0x3c, 0x87, 0xde, 0xa5,
	0x7d, 0x76, 0xc4, 0xdd, 0x5c, 0x78, 0xf2, 0xd3, 0xf5, 0x46, 0x0e, 0xce, 0xdb, 0xb0, 0xaa, 0xdd,
	0x23, 0x21, 0xeb, 0x21, 0x95, 0x9f, 0xcb, 0x29, 0x69, 0x6b, 0xda, 0x21, 0x4b, 0x6e, 0x70, 0xcb,
	0xb8, 0x90, 0xd6, 0x6b, 0xf1, 0x21, 0xbf, 0xbc, 0x07, 0x07, 0xa9, 0xb0, 0x13, 0xe8, 0x21, 0x85,
	0xc9, 0xf7, 0x90, 0x5a, 0xd3, 0x59, 0x77, 0x06, 0x47, 0xa3, 0x26, 0x57, 0x8f, 0x59, 0xe8, 0x4c,
	0x73, 0xe3, 0xb4, 0x73, 0xd2, 0xc7, 0x3f, 0xa5, 0x9d, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf5,
	0xac, 0x50, 0xd5, 0x36, 0x09, 0x00, 0x00,
}
