// Code generated by protoc-gen-go.
// source: nfs.proto
// DO NOT EDIT!

/*
Package nfs is a generated protocol buffer package.

It is generated from these files:
	nfs.proto

It has these top-level messages:
	FileHandle
	Attribute
	LookupArgs
	LookupReturn
	CreateArgs
	CreateReturn
	RemoveArgs
	RemoveReturn
	ReadArgs
	ReadReturn
	WriteArgs
	WriteReturn
*/
package nfs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// File handle type, need inode #, filesystem & generation #.
type FileHandle struct {
	Inode uint64 `protobuf:"varint,1,opt,name=inode" json:"inode,omitempty"`
	Genum uint64 `protobuf:"varint,2,opt,name=genum" json:"genum,omitempty"`
}

func (m *FileHandle) Reset()                    { *m = FileHandle{} }
func (m *FileHandle) String() string            { return proto.CompactTextString(m) }
func (*FileHandle) ProtoMessage()               {}
func (*FileHandle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Attribute struct {
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Hacky solution to multiple parameter, just follow convention: MethodNameArgs
type LookupArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *LookupArgs) Reset()                    { *m = LookupArgs{} }
func (m *LookupArgs) String() string            { return proto.CompactTextString(m) }
func (*LookupArgs) ProtoMessage()               {}
func (*LookupArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LookupArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

// Hacky solution to multiple retval, just follow convention: MethodNameReturn
type LookupReturn struct {
	Fh   *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Attr *Attribute  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *LookupReturn) Reset()                    { *m = LookupReturn{} }
func (m *LookupReturn) String() string            { return proto.CompactTextString(m) }
func (*LookupReturn) ProtoMessage()               {}
func (*LookupReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LookupReturn) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

func (m *LookupReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type CreateArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attr  *Attribute  `protobuf:"bytes,3,opt,name=attr" json:"attr,omitempty"`
}

func (m *CreateArgs) Reset()                    { *m = CreateArgs{} }
func (m *CreateArgs) String() string            { return proto.CompactTextString(m) }
func (*CreateArgs) ProtoMessage()               {}
func (*CreateArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

func (m *CreateArgs) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type CreateReturn struct {
	Newfh *FileHandle `protobuf:"bytes,1,opt,name=newfh" json:"newfh,omitempty"`
	Attr  *Attribute  `protobuf:"bytes,2,opt,name=attr" json:"attr,omitempty"`
}

func (m *CreateReturn) Reset()                    { *m = CreateReturn{} }
func (m *CreateReturn) String() string            { return proto.CompactTextString(m) }
func (*CreateReturn) ProtoMessage()               {}
func (*CreateReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateReturn) GetNewfh() *FileHandle {
	if m != nil {
		return m.Newfh
	}
	return nil
}

func (m *CreateReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type RemoveArgs struct {
	Dirfh *FileHandle `protobuf:"bytes,1,opt,name=dirfh" json:"dirfh,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *RemoveArgs) Reset()                    { *m = RemoveArgs{} }
func (m *RemoveArgs) String() string            { return proto.CompactTextString(m) }
func (*RemoveArgs) ProtoMessage()               {}
func (*RemoveArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveArgs) GetDirfh() *FileHandle {
	if m != nil {
		return m.Dirfh
	}
	return nil
}

type RemoveReturn struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *RemoveReturn) Reset()                    { *m = RemoveReturn{} }
func (m *RemoveReturn) String() string            { return proto.CompactTextString(m) }
func (*RemoveReturn) ProtoMessage()               {}
func (*RemoveReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ReadArgs struct {
	Fh     *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Offset int32       `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count  int32       `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *ReadArgs) Reset()                    { *m = ReadArgs{} }
func (m *ReadArgs) String() string            { return proto.CompactTextString(m) }
func (*ReadArgs) ProtoMessage()               {}
func (*ReadArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ReadArgs) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

type ReadReturn struct {
	Attr *Attribute `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
	Data []byte     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ReadReturn) Reset()                    { *m = ReadReturn{} }
func (m *ReadReturn) String() string            { return proto.CompactTextString(m) }
func (*ReadReturn) ProtoMessage()               {}
func (*ReadReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReadReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

type WriteArgs struct {
	Fh     *FileHandle `protobuf:"bytes,1,opt,name=fh" json:"fh,omitempty"`
	Offset int32       `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Count  int32       `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Data   []byte      `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *WriteArgs) Reset()                    { *m = WriteArgs{} }
func (m *WriteArgs) String() string            { return proto.CompactTextString(m) }
func (*WriteArgs) ProtoMessage()               {}
func (*WriteArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *WriteArgs) GetFh() *FileHandle {
	if m != nil {
		return m.Fh
	}
	return nil
}

// Yes, even for single retval's, follow convention for consistency
type WriteReturn struct {
	Attr *Attribute `protobuf:"bytes,1,opt,name=attr" json:"attr,omitempty"`
}

func (m *WriteReturn) Reset()                    { *m = WriteReturn{} }
func (m *WriteReturn) String() string            { return proto.CompactTextString(m) }
func (*WriteReturn) ProtoMessage()               {}
func (*WriteReturn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *WriteReturn) GetAttr() *Attribute {
	if m != nil {
		return m.Attr
	}
	return nil
}

func init() {
	proto.RegisterType((*FileHandle)(nil), "nfs.FileHandle")
	proto.RegisterType((*Attribute)(nil), "nfs.Attribute")
	proto.RegisterType((*LookupArgs)(nil), "nfs.LookupArgs")
	proto.RegisterType((*LookupReturn)(nil), "nfs.LookupReturn")
	proto.RegisterType((*CreateArgs)(nil), "nfs.CreateArgs")
	proto.RegisterType((*CreateReturn)(nil), "nfs.CreateReturn")
	proto.RegisterType((*RemoveArgs)(nil), "nfs.RemoveArgs")
	proto.RegisterType((*RemoveReturn)(nil), "nfs.RemoveReturn")
	proto.RegisterType((*ReadArgs)(nil), "nfs.ReadArgs")
	proto.RegisterType((*ReadReturn)(nil), "nfs.ReadReturn")
	proto.RegisterType((*WriteArgs)(nil), "nfs.WriteArgs")
	proto.RegisterType((*WriteReturn)(nil), "nfs.WriteReturn")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for NFS service

type NFSClient interface {
	// No null call for now (not sure if needed since grpc is smart itself!)
	Lookup(ctx context.Context, in *LookupArgs, opts ...grpc.CallOption) (*LookupReturn, error)
	Create(ctx context.Context, in *CreateArgs, opts ...grpc.CallOption) (*CreateReturn, error)
	Remove(ctx context.Context, in *RemoveArgs, opts ...grpc.CallOption) (*RemoveReturn, error)
	Read(ctx context.Context, in *ReadArgs, opts ...grpc.CallOption) (*ReadReturn, error)
	Write(ctx context.Context, in *WriteArgs, opts ...grpc.CallOption) (*WriteReturn, error)
}

type nFSClient struct {
	cc *grpc.ClientConn
}

func NewNFSClient(cc *grpc.ClientConn) NFSClient {
	return &nFSClient{cc}
}

func (c *nFSClient) Lookup(ctx context.Context, in *LookupArgs, opts ...grpc.CallOption) (*LookupReturn, error) {
	out := new(LookupReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Create(ctx context.Context, in *CreateArgs, opts ...grpc.CallOption) (*CreateReturn, error) {
	out := new(CreateReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Remove(ctx context.Context, in *RemoveArgs, opts ...grpc.CallOption) (*RemoveReturn, error) {
	out := new(RemoveReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Read(ctx context.Context, in *ReadArgs, opts ...grpc.CallOption) (*ReadReturn, error) {
	out := new(ReadReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nFSClient) Write(ctx context.Context, in *WriteArgs, opts ...grpc.CallOption) (*WriteReturn, error) {
	out := new(WriteReturn)
	err := grpc.Invoke(ctx, "/nfs.NFS/write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NFS service

type NFSServer interface {
	// No null call for now (not sure if needed since grpc is smart itself!)
	Lookup(context.Context, *LookupArgs) (*LookupReturn, error)
	Create(context.Context, *CreateArgs) (*CreateReturn, error)
	Remove(context.Context, *RemoveArgs) (*RemoveReturn, error)
	Read(context.Context, *ReadArgs) (*ReadReturn, error)
	Write(context.Context, *WriteArgs) (*WriteReturn, error)
}

func RegisterNFSServer(s *grpc.Server, srv NFSServer) {
	s.RegisterService(&_NFS_serviceDesc, srv)
}

func _NFS_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Lookup(ctx, req.(*LookupArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Create(ctx, req.(*CreateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Remove(ctx, req.(*RemoveArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Read(ctx, req.(*ReadArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _NFS_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NFSServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nfs.NFS/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NFSServer).Write(ctx, req.(*WriteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _NFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nfs.NFS",
	HandlerType: (*NFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "lookup",
			Handler:    _NFS_Lookup_Handler,
		},
		{
			MethodName: "create",
			Handler:    _NFS_Create_Handler,
		},
		{
			MethodName: "remove",
			Handler:    _NFS_Remove_Handler,
		},
		{
			MethodName: "read",
			Handler:    _NFS_Read_Handler,
		},
		{
			MethodName: "write",
			Handler:    _NFS_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("nfs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x0b, 0xda, 0x30,
	0x14, 0xb7, 0xda, 0x96, 0xf5, 0xb5, 0x9b, 0x5b, 0x18, 0x22, 0x5e, 0x36, 0x02, 0x0e, 0x61, 0x20,
	0xcc, 0x5d, 0x76, 0x95, 0x0d, 0xdd, 0x61, 0xec, 0x10, 0x0f, 0xc3, 0x63, 0xb4, 0xa9, 0x16, 0x35,
	0x91, 0x34, 0x9d, 0x5f, 0x7a, 0x1f, 0x62, 0xf4, 0x25, 0xb6, 0xbd, 0xe8, 0x04, 0x77, 0xcb, 0xcb,
	0xfb, 0xf1, 0xfb, 0x93, 0xf7, 0x5a, 0x88, 0x64, 0x56, 0x4c, 0xcf, 0x5a, 0x19, 0x45, 0x7a, 0x32,
	0x2b, 0xe8, 0x17, 0x80, 0x45, 0x7e, 0x14, 0xdf, 0xb9, 0x4c, 0x8f, 0x82, 0xbc, 0x85, 0x20, 0x97,
	0x2a, 0x15, 0x43, 0xef, 0xbd, 0x37, 0xf1, 0x99, 0x2d, 0xaa, 0xdb, 0x9d, 0x90, 0xe5, 0x69, 0xd8,
	0xb5, 0xb7, 0x58, 0xd0, 0x18, 0xa2, 0xb9, 0x31, 0x3a, 0xdf, 0x94, 0x46, 0xd0, 0x25, 0xc0, 0x0f,
	0xa5, 0x0e, 0xe5, 0x79, 0xae, 0x77, 0x05, 0x19, 0x43, 0x90, 0xe6, 0x3a, 0xdb, 0x23, 0x4d, 0x3c,
	0xeb, 0x4f, 0x2b, 0xd1, 0x46, 0x86, 0xd9, 0x2e, 0x21, 0xe0, 0x4b, 0x7e, 0x12, 0x48, 0x1b, 0x31,
	0x3c, 0xd3, 0x15, 0x24, 0x96, 0x88, 0x09, 0x53, 0x6a, 0x49, 0xde, 0x41, 0xf7, 0x36, 0x4f, 0x37,
	0xdb, 0x13, 0x0a, 0x3e, 0x37, 0x46, 0x23, 0x49, 0x3c, 0x7b, 0x85, 0x90, 0xda, 0x17, 0xc3, 0x1e,
	0x3d, 0x00, 0x7c, 0xd5, 0x82, 0x1b, 0xf1, 0xa4, 0xbb, 0x5a, 0xac, 0x77, 0x47, 0x6c, 0x0d, 0x89,
	0x15, 0x73, 0x09, 0xc6, 0x10, 0x48, 0x71, 0xb9, 0x23, 0x87, 0xdd, 0x87, 0x72, 0x2c, 0x01, 0x98,
	0x38, 0xa9, 0xdf, 0xcf, 0xe6, 0xa0, 0x1f, 0x20, 0xb1, 0x44, 0xce, 0xe3, 0x00, 0xc2, 0xc2, 0x70,
	0x53, 0x16, 0xc8, 0x15, 0x30, 0x57, 0xd1, 0x35, 0xbc, 0x60, 0x82, 0xa7, 0x28, 0xf7, 0xcf, 0x49,
	0x0c, 0x20, 0x54, 0x59, 0x56, 0x08, 0x83, 0x52, 0x01, 0x73, 0x55, 0xb5, 0x3e, 0x5b, 0x55, 0x4a,
	0x83, 0xaf, 0x16, 0x30, 0x5b, 0xd0, 0x6f, 0x55, 0x16, 0x9e, 0x3a, 0x03, 0xd7, 0xf4, 0xde, 0xed,
	0xf4, 0x55, 0x90, 0x94, 0x1b, 0x8e, 0xec, 0x09, 0xc3, 0x33, 0x95, 0x10, 0xfd, 0xd2, 0xb9, 0x1b,
	0xec, 0xff, 0x75, 0x58, 0xeb, 0xf9, 0x2d, 0xbd, 0x4f, 0x10, 0xa3, 0xde, 0xe3, 0xb6, 0x67, 0x7f,
	0x3c, 0xe8, 0xfd, 0x5c, 0xac, 0xc8, 0x14, 0xc2, 0x23, 0x6e, 0x36, 0xb1, 0xde, 0x9a, 0xef, 0x65,
	0xf4, 0xa6, 0x75, 0x61, 0x99, 0x69, 0xa7, 0xc2, 0x6f, 0x71, 0x8f, 0x1c, 0xbe, 0xd9, 0x60, 0x87,
	0x6f, 0x6f, 0x99, 0xc5, 0x6b, 0x9c, 0xa9, 0xc3, 0x37, 0x9b, 0xe2, 0xf0, 0xed, 0x89, 0xd3, 0x0e,
	0x99, 0x80, 0xaf, 0x05, 0x4f, 0xc9, 0x4b, 0xd7, 0xb4, 0x63, 0x1e, 0xf5, 0xeb, 0xb2, 0x46, 0x7e,
	0x84, 0xe0, 0x52, 0x85, 0x26, 0x36, 0x60, 0xfd, 0xe0, 0xa3, 0xd7, 0x4d, 0x7d, 0x05, 0x6f, 0x42,
	0xfc, 0xb9, 0x7c, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xee, 0x3e, 0xbf, 0x69, 0x04, 0x00,
	0x00,
}
