/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Calculator_H
#define Calculator_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "tutorial_types.h"
#include "SharedService.h"

namespace tutorial {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CalculatorIf : virtual public  ::shared::SharedServiceIf {
 public:
  virtual ~CalculatorIf() {}

  /**
   * A method definition looks like C code. It has a return type, arguments,
   * and optionally a list of exceptions that it may throw. Note that argument
   * lists and exception lists are specified using the exact same syntax as
   * field lists in struct or exception definitions.
   */
  virtual void ping() = 0;
  virtual int32_t int_time(const int32_t num1) = 0;
  virtual int32_t dbl_time(const double num1) = 0;
  virtual int32_t str_time(const std::string& str1) = 0;
  virtual int32_t bla_time(const Blah& b1) = 0;
  virtual int32_t calculate(const int32_t logid, const Work& w) = 0;

  /**
   * This method has a oneway modifier. That means the client only makes
   * a request and does not listen for any response at all. Oneway methods
   * must be void.
   */
  virtual void zip() = 0;
};

class CalculatorIfFactory : virtual public  ::shared::SharedServiceIfFactory {
 public:
  typedef CalculatorIf Handler;

  virtual ~CalculatorIfFactory() {}

  virtual CalculatorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler( ::shared::SharedServiceIf* /* handler */) = 0;
};

class CalculatorIfSingletonFactory : virtual public CalculatorIfFactory {
 public:
  CalculatorIfSingletonFactory(const boost::shared_ptr<CalculatorIf>& iface) : iface_(iface) {}
  virtual ~CalculatorIfSingletonFactory() {}

  virtual CalculatorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler( ::shared::SharedServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<CalculatorIf> iface_;
};

class CalculatorNull : virtual public CalculatorIf , virtual public  ::shared::SharedServiceNull {
 public:
  virtual ~CalculatorNull() {}
  void ping() {
    return;
  }
  int32_t int_time(const int32_t /* num1 */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t dbl_time(const double /* num1 */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t str_time(const std::string& /* str1 */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t bla_time(const Blah& /* b1 */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t calculate(const int32_t /* logid */, const Work& /* w */) {
    int32_t _return = 0;
    return _return;
  }
  void zip() {
    return;
  }
};


class Calculator_ping_args {
 public:

  Calculator_ping_args(const Calculator_ping_args&);
  Calculator_ping_args& operator=(const Calculator_ping_args&);
  Calculator_ping_args() {
  }

  virtual ~Calculator_ping_args() throw();

  bool operator == (const Calculator_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Calculator_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_ping_pargs {
 public:


  virtual ~Calculator_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_ping_result {
 public:

  Calculator_ping_result(const Calculator_ping_result&);
  Calculator_ping_result& operator=(const Calculator_ping_result&);
  Calculator_ping_result() {
  }

  virtual ~Calculator_ping_result() throw();

  bool operator == (const Calculator_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Calculator_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_ping_presult {
 public:


  virtual ~Calculator_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_int_time_args__isset {
  _Calculator_int_time_args__isset() : num1(false) {}
  bool num1 :1;
} _Calculator_int_time_args__isset;

class Calculator_int_time_args {
 public:

  Calculator_int_time_args(const Calculator_int_time_args&);
  Calculator_int_time_args& operator=(const Calculator_int_time_args&);
  Calculator_int_time_args() : num1(0) {
  }

  virtual ~Calculator_int_time_args() throw();
  int32_t num1;

  _Calculator_int_time_args__isset __isset;

  void __set_num1(const int32_t val);

  bool operator == (const Calculator_int_time_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    return true;
  }
  bool operator != (const Calculator_int_time_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_int_time_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_int_time_pargs {
 public:


  virtual ~Calculator_int_time_pargs() throw();
  const int32_t* num1;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_int_time_result__isset {
  _Calculator_int_time_result__isset() : success(false) {}
  bool success :1;
} _Calculator_int_time_result__isset;

class Calculator_int_time_result {
 public:

  Calculator_int_time_result(const Calculator_int_time_result&);
  Calculator_int_time_result& operator=(const Calculator_int_time_result&);
  Calculator_int_time_result() : success(0) {
  }

  virtual ~Calculator_int_time_result() throw();
  int32_t success;

  _Calculator_int_time_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_int_time_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_int_time_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_int_time_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_int_time_presult__isset {
  _Calculator_int_time_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_int_time_presult__isset;

class Calculator_int_time_presult {
 public:


  virtual ~Calculator_int_time_presult() throw();
  int32_t* success;

  _Calculator_int_time_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_dbl_time_args__isset {
  _Calculator_dbl_time_args__isset() : num1(false) {}
  bool num1 :1;
} _Calculator_dbl_time_args__isset;

class Calculator_dbl_time_args {
 public:

  Calculator_dbl_time_args(const Calculator_dbl_time_args&);
  Calculator_dbl_time_args& operator=(const Calculator_dbl_time_args&);
  Calculator_dbl_time_args() : num1(0) {
  }

  virtual ~Calculator_dbl_time_args() throw();
  double num1;

  _Calculator_dbl_time_args__isset __isset;

  void __set_num1(const double val);

  bool operator == (const Calculator_dbl_time_args & rhs) const
  {
    if (!(num1 == rhs.num1))
      return false;
    return true;
  }
  bool operator != (const Calculator_dbl_time_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_dbl_time_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_dbl_time_pargs {
 public:


  virtual ~Calculator_dbl_time_pargs() throw();
  const double* num1;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_dbl_time_result__isset {
  _Calculator_dbl_time_result__isset() : success(false) {}
  bool success :1;
} _Calculator_dbl_time_result__isset;

class Calculator_dbl_time_result {
 public:

  Calculator_dbl_time_result(const Calculator_dbl_time_result&);
  Calculator_dbl_time_result& operator=(const Calculator_dbl_time_result&);
  Calculator_dbl_time_result() : success(0) {
  }

  virtual ~Calculator_dbl_time_result() throw();
  int32_t success;

  _Calculator_dbl_time_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_dbl_time_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_dbl_time_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_dbl_time_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_dbl_time_presult__isset {
  _Calculator_dbl_time_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_dbl_time_presult__isset;

class Calculator_dbl_time_presult {
 public:


  virtual ~Calculator_dbl_time_presult() throw();
  int32_t* success;

  _Calculator_dbl_time_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_str_time_args__isset {
  _Calculator_str_time_args__isset() : str1(false) {}
  bool str1 :1;
} _Calculator_str_time_args__isset;

class Calculator_str_time_args {
 public:

  Calculator_str_time_args(const Calculator_str_time_args&);
  Calculator_str_time_args& operator=(const Calculator_str_time_args&);
  Calculator_str_time_args() : str1() {
  }

  virtual ~Calculator_str_time_args() throw();
  std::string str1;

  _Calculator_str_time_args__isset __isset;

  void __set_str1(const std::string& val);

  bool operator == (const Calculator_str_time_args & rhs) const
  {
    if (!(str1 == rhs.str1))
      return false;
    return true;
  }
  bool operator != (const Calculator_str_time_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_str_time_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_str_time_pargs {
 public:


  virtual ~Calculator_str_time_pargs() throw();
  const std::string* str1;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_str_time_result__isset {
  _Calculator_str_time_result__isset() : success(false) {}
  bool success :1;
} _Calculator_str_time_result__isset;

class Calculator_str_time_result {
 public:

  Calculator_str_time_result(const Calculator_str_time_result&);
  Calculator_str_time_result& operator=(const Calculator_str_time_result&);
  Calculator_str_time_result() : success(0) {
  }

  virtual ~Calculator_str_time_result() throw();
  int32_t success;

  _Calculator_str_time_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_str_time_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_str_time_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_str_time_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_str_time_presult__isset {
  _Calculator_str_time_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_str_time_presult__isset;

class Calculator_str_time_presult {
 public:


  virtual ~Calculator_str_time_presult() throw();
  int32_t* success;

  _Calculator_str_time_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_bla_time_args__isset {
  _Calculator_bla_time_args__isset() : b1(false) {}
  bool b1 :1;
} _Calculator_bla_time_args__isset;

class Calculator_bla_time_args {
 public:

  Calculator_bla_time_args(const Calculator_bla_time_args&);
  Calculator_bla_time_args& operator=(const Calculator_bla_time_args&);
  Calculator_bla_time_args() {
  }

  virtual ~Calculator_bla_time_args() throw();
  Blah b1;

  _Calculator_bla_time_args__isset __isset;

  void __set_b1(const Blah& val);

  bool operator == (const Calculator_bla_time_args & rhs) const
  {
    if (!(b1 == rhs.b1))
      return false;
    return true;
  }
  bool operator != (const Calculator_bla_time_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_bla_time_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_bla_time_pargs {
 public:


  virtual ~Calculator_bla_time_pargs() throw();
  const Blah* b1;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_bla_time_result__isset {
  _Calculator_bla_time_result__isset() : success(false) {}
  bool success :1;
} _Calculator_bla_time_result__isset;

class Calculator_bla_time_result {
 public:

  Calculator_bla_time_result(const Calculator_bla_time_result&);
  Calculator_bla_time_result& operator=(const Calculator_bla_time_result&);
  Calculator_bla_time_result() : success(0) {
  }

  virtual ~Calculator_bla_time_result() throw();
  int32_t success;

  _Calculator_bla_time_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Calculator_bla_time_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Calculator_bla_time_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_bla_time_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_bla_time_presult__isset {
  _Calculator_bla_time_presult__isset() : success(false) {}
  bool success :1;
} _Calculator_bla_time_presult__isset;

class Calculator_bla_time_presult {
 public:


  virtual ~Calculator_bla_time_presult() throw();
  int32_t* success;

  _Calculator_bla_time_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Calculator_calculate_args__isset {
  _Calculator_calculate_args__isset() : logid(false), w(false) {}
  bool logid :1;
  bool w :1;
} _Calculator_calculate_args__isset;

class Calculator_calculate_args {
 public:

  Calculator_calculate_args(const Calculator_calculate_args&);
  Calculator_calculate_args& operator=(const Calculator_calculate_args&);
  Calculator_calculate_args() : logid(0) {
  }

  virtual ~Calculator_calculate_args() throw();
  int32_t logid;
  Work w;

  _Calculator_calculate_args__isset __isset;

  void __set_logid(const int32_t val);

  void __set_w(const Work& val);

  bool operator == (const Calculator_calculate_args & rhs) const
  {
    if (!(logid == rhs.logid))
      return false;
    if (!(w == rhs.w))
      return false;
    return true;
  }
  bool operator != (const Calculator_calculate_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_calculate_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_calculate_pargs {
 public:


  virtual ~Calculator_calculate_pargs() throw();
  const int32_t* logid;
  const Work* w;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_calculate_result__isset {
  _Calculator_calculate_result__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _Calculator_calculate_result__isset;

class Calculator_calculate_result {
 public:

  Calculator_calculate_result(const Calculator_calculate_result&);
  Calculator_calculate_result& operator=(const Calculator_calculate_result&);
  Calculator_calculate_result() : success(0) {
  }

  virtual ~Calculator_calculate_result() throw();
  int32_t success;
  InvalidOperation ouch;

  _Calculator_calculate_result__isset __isset;

  void __set_success(const int32_t val);

  void __set_ouch(const InvalidOperation& val);

  bool operator == (const Calculator_calculate_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(ouch == rhs.ouch))
      return false;
    return true;
  }
  bool operator != (const Calculator_calculate_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_calculate_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Calculator_calculate_presult__isset {
  _Calculator_calculate_presult__isset() : success(false), ouch(false) {}
  bool success :1;
  bool ouch :1;
} _Calculator_calculate_presult__isset;

class Calculator_calculate_presult {
 public:


  virtual ~Calculator_calculate_presult() throw();
  int32_t* success;
  InvalidOperation ouch;

  _Calculator_calculate_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class Calculator_zip_args {
 public:

  Calculator_zip_args(const Calculator_zip_args&);
  Calculator_zip_args& operator=(const Calculator_zip_args&);
  Calculator_zip_args() {
  }

  virtual ~Calculator_zip_args() throw();

  bool operator == (const Calculator_zip_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Calculator_zip_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Calculator_zip_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Calculator_zip_pargs {
 public:


  virtual ~Calculator_zip_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class CalculatorClient : virtual public CalculatorIf, public  ::shared::SharedServiceClient {
 public:
  CalculatorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
     ::shared::SharedServiceClient(prot, prot) {}
  CalculatorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :     ::shared::SharedServiceClient(iprot, oprot) {}
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  int32_t int_time(const int32_t num1);
  void send_int_time(const int32_t num1);
  int32_t recv_int_time();
  int32_t dbl_time(const double num1);
  void send_dbl_time(const double num1);
  int32_t recv_dbl_time();
  int32_t str_time(const std::string& str1);
  void send_str_time(const std::string& str1);
  int32_t recv_str_time();
  int32_t bla_time(const Blah& b1);
  void send_bla_time(const Blah& b1);
  int32_t recv_bla_time();
  int32_t calculate(const int32_t logid, const Work& w);
  void send_calculate(const int32_t logid, const Work& w);
  int32_t recv_calculate();
  void zip();
  void send_zip();
};

class CalculatorProcessor : public  ::shared::SharedServiceProcessor {
 protected:
  boost::shared_ptr<CalculatorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CalculatorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_int_time(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_dbl_time(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_str_time(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_bla_time(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_calculate(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_zip(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CalculatorProcessor(boost::shared_ptr<CalculatorIf> iface) :
     ::shared::SharedServiceProcessor(iface),
    iface_(iface) {
    processMap_["ping"] = &CalculatorProcessor::process_ping;
    processMap_["int_time"] = &CalculatorProcessor::process_int_time;
    processMap_["dbl_time"] = &CalculatorProcessor::process_dbl_time;
    processMap_["str_time"] = &CalculatorProcessor::process_str_time;
    processMap_["bla_time"] = &CalculatorProcessor::process_bla_time;
    processMap_["calculate"] = &CalculatorProcessor::process_calculate;
    processMap_["zip"] = &CalculatorProcessor::process_zip;
  }

  virtual ~CalculatorProcessor() {}
};

class CalculatorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CalculatorProcessorFactory(const ::boost::shared_ptr< CalculatorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CalculatorIfFactory > handlerFactory_;
};

class CalculatorMultiface : virtual public CalculatorIf, public  ::shared::SharedServiceMultiface {
 public:
  CalculatorMultiface(std::vector<boost::shared_ptr<CalculatorIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<boost::shared_ptr<CalculatorIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
       ::shared::SharedServiceMultiface::add(*iter);
    }
  }
  virtual ~CalculatorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CalculatorIf> > ifaces_;
  CalculatorMultiface() {}
  void add(boost::shared_ptr<CalculatorIf> iface) {
     ::shared::SharedServiceMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  int32_t int_time(const int32_t num1) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->int_time(num1);
    }
    return ifaces_[i]->int_time(num1);
  }

  int32_t dbl_time(const double num1) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->dbl_time(num1);
    }
    return ifaces_[i]->dbl_time(num1);
  }

  int32_t str_time(const std::string& str1) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->str_time(str1);
    }
    return ifaces_[i]->str_time(str1);
  }

  int32_t bla_time(const Blah& b1) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->bla_time(b1);
    }
    return ifaces_[i]->bla_time(b1);
  }

  int32_t calculate(const int32_t logid, const Work& w) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->calculate(logid, w);
    }
    return ifaces_[i]->calculate(logid, w);
  }

  void zip() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->zip();
    }
    ifaces_[i]->zip();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CalculatorConcurrentClient : virtual public CalculatorIf, public  ::shared::SharedServiceConcurrentClient {
 public:
  CalculatorConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
     ::shared::SharedServiceConcurrentClient(prot, prot) {}
  CalculatorConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :     ::shared::SharedServiceConcurrentClient(iprot, oprot) {}
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  int32_t int_time(const int32_t num1);
  int32_t send_int_time(const int32_t num1);
  int32_t recv_int_time(const int32_t seqid);
  int32_t dbl_time(const double num1);
  int32_t send_dbl_time(const double num1);
  int32_t recv_dbl_time(const int32_t seqid);
  int32_t str_time(const std::string& str1);
  int32_t send_str_time(const std::string& str1);
  int32_t recv_str_time(const int32_t seqid);
  int32_t bla_time(const Blah& b1);
  int32_t send_bla_time(const Blah& b1);
  int32_t recv_bla_time(const int32_t seqid);
  int32_t calculate(const int32_t logid, const Work& w);
  int32_t send_calculate(const int32_t logid, const Work& w);
  int32_t recv_calculate(const int32_t seqid);
  void zip();
  void send_zip();
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
